### ISSUE TITLE
Post to channel remotely with Macbot email

### ISSUE THREAD

**Issue by rthrblck** [madcollective/macbot#29]
In order to keep a team up to date with client communications, it would be great to give Macbot a functioning email address so that when a client is emailed concerning a project, Macbot can be BCC'd with the channel name, and will then post in the appropriate Slack channel.

**Comment by rthrblck** [comment]
Two potential solutions, both of which I think are deployed to Heroku:

Postmark: https://addons.heroku.com/postmark
Mail2Webhook: https://devcenter.heroku.com/articles/mail2webhook

**Comment by christianbundy** [comment]
It looks like Postmark is a mature third-party that allows you to send and receive emails, whereas Mail2Webhook is a super-simple lightweight service that only receives emails.

Both give you a **single**, computer-generated email address that you can receive emails at, meaning that we'll have to start by parsing the subject line (or something like that). In the future we could totally set up a routing service that acts as a load balancer for multiple email addresses in front of the app, but for now we'll have to embrace the jankiness.

My proposal for next steps:
- [ ] Create GitHub project
- [ ] Clone GitHub project locally
- [ ] Move this issue to new GitHub project
- [ ] Create Heroku project
- [ ] Unarchive testing channel
- [ ] Install Mail2Webhook with stock functionality
- [ ] Deploy to Heroku
- [ ] Test!
- [ ] Push to GitHub
- [ ] Create issue for posting to a channel, and iterate with standard GitHub flow

**Comment by rthrblck** [comment]
This feature has already been very nicely made, including a free account up to 250 emails per month. 

https://www.getfranke.com/

Closing issue.
