### ISSUE TITLE
Macbot not shouting in channel

### ISSUE THREAD

**Issue by christianbundy** [madcollective/macbot#31]
`@channel` is being used as text, but there's no notification.

https://slack.zendesk.com/hc/en-us/articles/202009646-Using-channel-group-everyone

I'm not sure whether we should be using `<!everyone>` or `!everyone`, but neither are working when I'm testing with Slackbot (although Hubot could be different).

**Comment by rthrblck** [comment]
Resolved with proper syntax for bot shouting in Slack <!tag>
